macOS compatibility
InteractiveComputerGraphics/SPlisHSPlasH pull request #167
Opened 2022-04-09 11:33 UTC by ruberith

These adaptations allow builds using Clang on recent versions of macOS (tested on Apple silicon):

- Updated and adapted versions of CompactNSearch, Discregrid and PositionBasedDynamics are used (see [CompactNSearch#7](https://github.com/InteractiveComputerGraphics/CompactNSearch/pull/7), [Discregrid#19](https://github.com/InteractiveComputerGraphics/Discregrid/pull/19) and [PositionBasedDynamics#124](https://github.com/InteractiveComputerGraphics/PositionBasedDynamics/pull/124)). If the pull requests are accepted, `CMake/NeighborhoodSearch.cmake` and `CMake/SetUpExternalProjects.cmake` have to be updated to point to the original repositories again.
- Clang seems to mistake some version files for headers, so these are given an extension.
- The optimization flag `-mcpu=apple-m1` is used for Apple silicon, for which `-march=native` is not yet supported.
- OpenGL is deprecated for years on macOS, but still supported, so the corresponding warnings are silenced.
- `_NSGetExecutablePath` is used to find program paths on macOS.
- numpy is available for Apple silicon since version 1.21.0. The highest supported version can possibly be updated in `setup.py`.
- AVX is disabled for ARM.
- Catch2 is updated to v2.13.8.
- Clang adheres [more closely to the C++ standard regarding lookups](https://clang.llvm.org/compatibility.html#dep_lookup), so overloaded operators with template parameters are moved to the namespace `std`.
- Higher versions of OpenGL are only supported with core profiles on macOS which are not compatible with removed functionality. Since MiniGL follows the fixed function pipeline, OpenGL has to fall back to version 2.1. In this case, the corresponding implementation of ImGui is now used.
- Recent versions of CMake automatically determine the correct flags for OpenMP and provide a target to link against. Nevertheless, Clang does not include an OpenMP implementation on macOS by default, but the user can easily install a build of LLVM libomp (e.g. via Homebrew) to be shared by all projects requiring OpenMP which is then detected by CMake.

2022-05-21 12:49 UTC, ruberith commented
To allow for the same visual experience on all platforms, I now have ported MiniGL to the OpenGL 3.3 Core Profile by replacing all fixed-function calls with "modern" equivalents.

2022-06-11 09:48 UTC, ruberith commented
AVX is now supported on ARM via [SIMDe](https://github.com/simd-everywhere/simde) which forwards to the native intrinsics on x86 and provides equivalent implementations using NEON on ARM.

2022-07-30 19:41 UTC, ruberith commented
After further testing, I couldn't spot a noticeable performance difference with the SIMD option active, so I removed the dependency on SIMDe again. As [recommended by Apple](https://developer.apple.com/documentation/apple-silicon/addressing-architectural-differences-in-your-macos-code), I substituted the intrinsics in the AVX math wrapper with equivalent calls to the Accelerate framework for macOS systems which yielded the expected performance boost. Since I do not have an Intel Mac, I could not check whether the existing AVX calls or Accelerate calls are faster or if effectively the same intrinsics are used; the implementation details of the framework calls are only partially accessible.

2022-08-06 19:37 UTC, digitalillusions commented
Ok, so I can confirm that this indeed compiles for me on an M2 macbook air. I will also make another attempt using the intel macbook air in a couple of days.

2022-08-26 09:03 UTC, digitalillusions commented
So I confirmed that this works on both an intel macbook air and an m2 macbook air. I think we should consider merging this soon since there were multiple requests for macos compatibility in the past. It should just be noted that its hard for us to maintain macos compatibility and that this will probably have to be done by the community.

2022-08-29 15:44 UTC, ruberith commented
@digitalillusions Thank you for verifying. I have just merged in the latest updates, so together with [CompactNSearch#7](https://github.com/InteractiveComputerGraphics/CompactNSearch/pull/7), [Discregrid#19](https://github.com/InteractiveComputerGraphics/Discregrid/pull/19) and [PositionBasedDynamics#123](https://github.com/InteractiveComputerGraphics/PositionBasedDynamics/pull/123), the compatibility should be ensured for now.

2022-09-28 11:52 UTC, digitalillusions commented
So we went through the PR in a bit more detail and were wondering if all of the proposed changes are actually strictly necessary to make it functional. Specifically, are all the changes to the GUI system and shaders actually necessary? Also, is the change to the alignment allocator necessary? 

If not, would it be possible for you to split up the PR into changes actually required to run on MacOS, and optional improvements.

2022-09-28 17:07 UTC, ruberith commented
macOS does unfortunately only support the core profile of OpenGL 3.3, in which the fixed function calls (including GLU) [do not work](https://www.khronos.org/opengl/wiki/Fixed_Function_Pipeline). All changes are specific replacements of these calls according to their documentation to have the same visual experience.
Similarly, for AVX compatibility on macOS ARM, I used equivalent calls from the Accelerate framework. Concerning the alignment allocator, I ran into errors when not choosing the exact alignment of the underlying data structure (16 bytes for Accelerate's simd::float8), even if 32 bytes are supposed to be fine. This seems to be fixed in a recent version of Apple Clang, so I will revert these changes.

2022-11-28 13:51 UTC, digitalillusions commented on GUI/OpenGL/MiniGL.cpp
> +	glVertexAttrib3f(1, 0.0, 0.0, 1.0);
Why is the attribute set to (0,0,1)? Does this supply some default "normal" value?

2022-11-28 13:55 UTC, digitalillusions commented on GUI/OpenGL/MiniGL.cpp
> +	drawVector(Vector3r(2.0, 0.0, 0.0), Vector3r(size, 0.0, 0.0), lineWidth, color);
the offset of 2 is for avoiding the overlap with the coordinate axis, correct?

also, it seems a bit overcomplicated to render lines as cylinders, also for the coordinates. would it be possible to just render as lines?

2022-11-28 14:29 UTC, digitalillusions commented on Simulator/GUI/OpenGL/Simulator_OpenGL.cpp
> +		MiniGL::supplyFaces(selectedParticles[fluidIndex].size(), selectedParticles[fluidIndex].data());
how does this actually render the selected particles?

2022-11-28 14:37 UTC, digitalillusions requested changes
Very nice job, thanks for the PR! Overall the changes look good to us. I think having some comments at the specified places would be helpful for future understanding of the code. 

Also, we are currently working on some new features for splishsplash, so merging the PR will probably be delayed until after the new version is released. Once its released, you could rebase and then there should be no problem merging the PR.

2022-11-28 14:37 UTC, digitalillusions commented on CMakeLists.txt
> +	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -idirafter${EIGEN3_INCLUDE_DIR}")
Is this also tested with "regular" Clang and not just AppleClang? Otherwise the branch should probably be only applied to appleclang.

2022-11-28 14:37 UTC, digitalillusions commented on Utilities/CMakeLists.txt
> +if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
also question about clang

2022-12-01 14:48 UTC, ruberith commented on GUI/OpenGL/MiniGL.cpp
> +	glVertexAttrib3f(1, 0.0, 0.0, 1.0);
Yes, this is the same default value as used for the original fixed-function call [glNormal](https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glNormal.xml).

2022-12-01 15:35 UTC, ruberith commented on GUI/OpenGL/MiniGL.cpp
> +	drawVector(Vector3r(2.0, 0.0, 0.0), Vector3r(size, 0.0, 0.0), lineWidth, color);
You are right.
Using [glLineWidth](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glLineWidth.xhtml), only a line width of 1 is guaranteed to be supported. With the macOS OpenGL core profile, I haven't been able to render thicker lines this way, so I have chosen the cylinder representation. There exist alternatives using shaders that are more performant but also more complex to implement. Given the current approach of rendering each object separately, this should not have a major impact on performance.

2022-12-01 17:06 UTC, ruberith commented on CMakeLists.txt
> +	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -idirafter${EIGEN3_INCLUDE_DIR}")
This should apply to regular Clang as well since it also [supports `<version>` headers](https://en.cppreference.com/w/cpp/compiler_support#C.2B.2B20_library_features). However, I haven't been able to verify this yet, as CompactNSearch is missing a parallel foreach implementation for Clang on other platforms.

2022-12-01 17:20 UTC, ruberith commented
Thank you for the review. I will check where I can add comments in the code for clarification.

2023-03-06 16:34 UTC, digitalillusions commented
Thanks @ruberith for your continued efforts! It seems good to me so far, but somehow the selection box does not align correctly with the mouse position for me on macos. Have you encountered something similar? Tbf it seems to work on linux and windows.

2023-03-12 15:44 UTC, ruberith commented
This was due to retina displays having a framebuffer size of double the window size and should now be fixed. I have an external monitor connected, so I didn't notice that, thank you. :D Feel free to tell me if there is anything else I should change. Otherwise I would rebase as suggested for a clearer commit history.

2023-03-13 17:07 UTC, digitalillusions commented
Thanks for all the hard work! It would have probably taken me ages to find that particular problem! The changes look good to me, the only other minor problem that I experience is that key presses dont seem to be captured if you launch splishsplash with the interactive file selector. I.e. if you directly pass a file on the command line everything works as expected. However, if you just run the program and use the native file dialogue, the key presses dont do anything. Can you also reproduce this?

2023-03-14 20:33 UTC, ruberith commented
The pull request is now rebased on top of the main branch. Regarding the issues with the file dialog, I found a [warning in the README of NFDe](https://github.com/btzy/nativefiledialog-extended#usage-with-a-platform-abstraction-framework) that might apply. When a scene file is specified on the command line, so that NFDe is initialized after GLFW, everything seems to work just fine if, for instance, a state file is loaded via the file dialog.

2023-05-05 15:14 UTC, ruberith commented
Unfortunately, I can not reproduce the first error. Using the latest versions of Apple Clang, CMake, and miniconda with Python 3.8, the interop builds and works in both directions on my system. I get the visibility warnings as well; however, they have no impact on the functionality of the bindings.

The second problem is [to be expected](https://www.khronos.org/opengl/wiki/Common_Mistakes#The_Object_Oriented_Language_Problem) as `~Shader` is called after the destruction of the context by `glfwDestroyWindow`. I don't know why the application only segfaults on Linux, but we are here in the territory of undefined behavior. :D The latest commit should ensure that everything is destroyed properly.

2024-09-24 19:10 UTC, ruberith commented
I‘ve added some minor fixes for double-precision builds and rebased to bring the PR in a mergeable state again. After reviewing this PR and merging [CompactNSearch#10](https://github.com/InteractiveComputerGraphics/CompactNSearch/pull/10) or [CompactNSearch#11](https://github.com/InteractiveComputerGraphics/CompactNSearch/pull/11), I could also squash everything together into one single commit if you‘d like me to.

2025-07-02 13:46 UTC, digitalillusions approved these changes
lgtm and seems to work like this. we will have to address cmake updates in a separate PR and might also include the default install dir for openmp on mac, which is `/opt/homebrew/opt/libomp` I believe. hopefully we can get around to merging soon.

2025-08-12 13:58 UTC, merged